---
- name: "Copy warning file (pre-login)"
  ansible.builtin.copy:
    src: login.warn
    dest: /etc/login.warn
    mode: "0644"
    owner: root
    group: root

- name: "Copy over login banner file (post-login)"
  ansible.builtin.template:
    src: motd.j2
    dest: /etc/motd
    mode: "0644"
    owner: root
    group: root

- name: "Remove default motd directory"
  ansible.builtin.file:
    path: /etc/update-motd.d
    state: absent

