---
- name: "Base configuration"
  block:
    - name: "Update"
      ansible.builtin.include_tasks: updates.yml

    - name: "Banner"
      ansible.builtin.include_tasks: banner.yml

    - name: "SSH"
      ansible.builtin.include_tasks: ssh.yml

    - name: "Tools"
      ansible.builtin.include_tasks: tools.yml
