---
- name: "Install useful packages"
  apt:
    name:
      - git
      - bash-completion
      - jq
      - acl # https://stackoverflow.com/questions/46352173/ansible-failed-to-set-permissions-on-the-temporary
      - python3-pip
    state: present
    update_cache: true
