---
- name: "Upgrade all packages"
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
    only_upgrade: true

- name: "Check if reboot is required"
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: stat_result

- name: "Restart if needed"
  ansible.builtin.reboot:
  when: stat_result.stat.exists
