---
- name: "Upgrade all packages"
  apt:
    name: "*"
    state: latest
    update_cache: true

- name: "Check if reboot is required"
  stat:
    path: /var/run/reboot-required
  register: stat_result

- name: "Restart if needed"
  reboot:
  when: stat_result.stat.exists
