service:
  annotations:
    metallb.io/loadBalancerIPs: 10.1.2.205
ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
  websecure:
    address: ":443/tcp"
    transport:
      lifeCycle:
        requestAcceptGraceTimeout: 10s
      forwardingTimeouts:
        idleTimeout: 0s
ingressRoute:
  dashboard:
    enabled: true
    entryPoints: [ web, websecure ]
    matchRule: Host(`traefik.clinch-home.com`)
    tls:
      secretName: traefik-certificate-secret
providers:
  kubernetesIngress:
    allowExternalNameServices: true
global:
  sendAnonymousUsage: true