---
- name: Ensure apt keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Download Grafana GPG key
  ansible.builtin.get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /etc/apt/keyrings/grafana.asc
    owner: root
    group: root
    mode: "0644"

- name: Add Grafana apt repository
  ansible.builtin.apt_repository:
    # yamllint disable-line rule:line-length
    repo: "deb [signed-by=/etc/apt/keyrings/grafana.asc] https://apt.grafana.com stable main"
    filename: grafana

- name: Install Grafana Alloy
  ansible.builtin.apt:
    name: "alloy={{ monitoring_alloy_version }}"
    state: present
