---
apiVersion: v1
kind: Namespace
metadata:
  name: factorio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorio
  namespace: factorio
  labels:
    name: factorio
spec:
  replicas: 1
  selector:
    matchLabels:
      name: factorio
  template:
    metadata:
      labels:
        name: factorio
    spec:
      initContainers:
        - name: copy-server-settings
          image: busybox
          command: [ "sh", "-c", "mkdir -p /factorio/config && cp /configmap/server-settings.json /factorio/config/server-settings.json" ]
          volumeMounts:
            - name: factorio
              mountPath: /factorio
            - name: server-settings
              mountPath: /configmap
      containers:
        - name: factorio
          image: factoriotools/factorio:2.0.47
          ports:
            - containerPort: 34197
              protocol: UDP
          env:
            - name: DLC_SPACE_AGE
              value: "true"
          resources:
            requests:
              cpu: "4"
              memory: "16Gi"
          volumeMounts:
            - mountPath: /factorio
              name: factorio
      volumes:
        - name: factorio
          persistentVolumeClaim:
            claimName: factorio
        - name: server-settings
          configMap:
            name: factorio-server-settings

---
apiVersion: v1
kind: Service
metadata:
  name: factorio
  namespace: factorio
  labels:
    name: factorio
spec:
  type: NodePort
  selector:
    name: factorio
  ports:
    - name: factorio-udp
      port: 34197
      targetPort: 34197
      nodePort: 31497
      protocol: UDP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio
  namespace: factorio
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: factorio-server-settings
  namespace: factorio
data:
  server-settings.json: |
    {
      "name": "blaze clage",
      "description": "clincha & blaze go to space",
      "tags": [
        "rad"
      ],
      "max_players": 2,
      "visibility": {
        "public": false,
        "lan": true
      },
      "autosave_interval": 5,
      "autosave_slots": 10,
      "afk_autokick_interval": 0,
      "auto_pause": true,
      "auto_pause_when_players_connect": false,
      "only_admins_can_pause_the_game": true,
      "autosave_only_on_server": true
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: factorio-map-settings
  namespace: factorio
data:
  server-settings.json: |
    {
      "name": "blaze clage",
      "description": "clincha & blaze go to space",
      "tags": [
        "rad"
      ],
      "max_players": 2,
      "visibility": {
        "public": false,
        "lan": true
      },
      "autosave_interval": 5,
      "autosave_slots": 10,
      "afk_autokick_interval": 0,
      "auto_pause": true,
      "auto_pause_when_players_connect": false,
      "only_admins_can_pause_the_game": true,
      "autosave_only_on_server": true
    }