Vagrant.configure("2") do |config|
  config.vm.box = "clincha/proxmox-ve-8"
  config.vm.box_version = "1.2.1"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
    vb.cpus = "4"
    vb.customize ["modifyvm", :id, "--nicpromisc1", "allow-all"]
  end
  config.vm.network "forwarded_port", id: "proxmox_web_gui", host: 8006, guest: 8006, host_ip: "0.0.0.0", guest_ip: "10.0.2.15"
  config.vm.network "forwarded_port", id: "ssh", host: 2222, guest: 22, host_ip: "0.0.0.0", guest_ip: "10.0.2.15"
  config.vm.network "forwarded_port", id: "ssh_guest", host: 2223, guest: 22, host_ip: "0.0.0.0", guest_ip: "10.0.2.16"

  config.vm.synced_folder "iso", "/var/lib/vz/template/iso"
end