---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: deliver
  namespace: flux-system
spec:
  interval: 5m
  ref:
    branch: master
  secretRef:
    name: deliver-ssh-key
  url: ssh://git@github.com/clincha/Deliver.git
