---
apiVersion: v1
kind: Namespace
metadata:
  name: github-runners-clincha
  labels:
    name: github-runners-clincha
---
apiVersion: v1
kind: Namespace
metadata:
  name: github-runners-elasticstar
  labels:
    name: github-runners-elasticstar