---
apiVersion: v1
kind: ConfigMap
metadata:
  name: github-runners-elasticstar-values
  namespace: flux-system
data:
  values.yaml: |
    githubConfigUrl: "https://github.com/clincha/ElasticStar"
    githubConfigSecret: "github-config-secret"
    minRunners: 1