apiVersion: v1
data:
    api-token: ENC[AES256_GCM,data:8jWYrA5117iVLnSXRyZSW0Ub6uMHJ8w0BPZ2eVrmFM4VLX+YBoCJB+IrmkIkZ7fUiKl5vFUBCeA=,iv:AnUKO4F60CiwkSCuICw/V5VZ04EdisrV09IU686uZVM=,tag:2uoP6bLxKWWFJuHqbfcBJA==,type:str]
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: certificate-manager
sops:
    lastmodified: "2025-09-04T11:40:06Z"
    mac: ENC[AES256_GCM,data:JvIRnNL5tXqcXBLbCJgYZNDyR+DFLMhq7P8VHfL9If4dT+UzrRVeAme5oyU3TPctMmJy6Jy/+lFgbLU0Pl5LDHbfT3s5HPeXe7oLNsEP2WDkD0kFslvvfoGijhouy6LaGt9lRqzgTpqp/trEXQNlXQu8A8S++wOsSZnJl72KpzQ=,iv:cSkoE9nQxV4TanHg9EmpVVx/KaIDVjAYMWTd1ZjDYuw=,tag:my1BrFtk0GJzYzS9OYbHig==,type:str]
    pgp:
        - created_at: "2025-09-04T11:40:06Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+iIV7UXPYO1ARAAtRqmYHIicQ28iQ34M13Gx5tz/qkLE3xeIVwcoNN3m54c
            x5dJKp8MnGxXfrE+H2u5FrjDLb5ox9hBAbgw57Jbw10+IIooD5knohCtt9rCPW3h
            ATI/QluFqIWGuMp6oM5egn1Bv2IlU+OhECJA4nIkuuMXVU9B1R3yuhqoyDrAI5Ee
            vtfcA1xJs0fk84ouWTzXifdhJWMwDdFupErX55S6L9uVxKzubywm4TvRAqYM8l1X
            CYLPb8RXf3wnE/sbqAyND8Es98elrOER0kpRwT0zooLYHDQrOIFrRgdyM+g44h7G
            cmsEuErVYvHCN6UI5w9z4LE7xkbCUlFI5YbI2kxlwn9SfuegsqMC9sg2HUw0GqQf
            fXGsNe8QAjkLF3UTGXTtmuuyme1ZwaHSfgm4XZv7Ypnu4IxqfLDaUlPS2cViYxTg
            xX+AxGUEmLee4AgDeqg/ZhdCyDHOdAObQ7jpefg6kppgdD2YeNRJ/ee976GcIUW8
            rppWLR9TPbaRv9QqZpPpKRNDS4IkVZBjUC5qS65eMt0ksce6YHhwf6yZig429GzT
            pI8F83zQXPjhX4xu6A8m9XCVRdBcaDIY5jn20KC4gd5f7fqiWSycT3h6HR807NSJ
            6I3NQfbZRka6OL1B6apUR+UAd7Y5/zQdW8KzrMtqtA2gD8rNZ/F+jy1+bjTLy7rS
            XgGxLlsLId79ny7KKyQqvhpIEjWO+OlnanReUm8DUfsXR/+Co8k5LMN3jROKoX4+
            szKHiohpRWqFf2KMdhVrTYmArtlhiqrW08pET+UOoPW1jDunfKHuHrXJyLCqDHA=
            =L6Ek
            -----END PGP MESSAGE-----
          fp: 76AF39813C2297E8F98C542D42436A07A9BA1DE0
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
