---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: certificate-manager
  namespace: certificate-manager
spec:
  targetNamespace: certificate-manager
  interval: 30m
  chart:
    spec:
      chart: cert-manager
      version: 'v1.21.0'
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: certificate-manager
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: certificate-manager-values
      valuesKey: values.yml