version: 2
updates:
  - package-ecosystem: pip
    directory: "/Ansible"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "ansible-core"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
  - package-ecosystem: github-actions
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
  - package-ecosystem: terraform
    directories:
      - "/terraform/kubernetes"
      - "/terraform/kubernetes/master"
    schedule:
      interval: "weekly"