version: 2
updates:
  - package-ecosystem: pip
    directory: "/Ansible"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "ansible-core"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
  - package-ecosystem: github-actions
    directories:
      - "/.github/workflows"
      - "/.github/actions/ansible-setup"
      - "/.github/actions/terraform-setup"
    schedule:
      interval: "weekly"
  - package-ecosystem: terraform
    directories:
      - "/terraform/hawkfield"
      - "/terraform/hawkfield-kubernetes"
      - "/terraform/london"
      - "/terraform/minio"
    schedule:
      interval: "weekly"