apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - serviceaccount.yml
  - nginx-conf.yml
  - deployment.yml
  - service.yml
  - ingress.yml
  - certificate.yml
  - network-policy.yml
