apiVersion: v1
kind: Secret
metadata:
    name: media-ssh-key
    namespace: flux-system
type: Opaque
stringData:
    identity: ENC[AES256_GCM,data:EeCk/f+V7MtaaUUSuGFlO/b/8iYMT3MaAJsSKoavdZNlrzP47363W49aI2rqOKH+QE6idgLQQqtVu/nSi7CWW5PctFNpaIqhkIXLhuL6G+xKordynXEHqtnH/FZqfBYzn5CIDoopP/tyJkoex6kQ3Zieibpets3U6s22jCSzJaArX/PTlVTHwRQTViIreEU2WFhxToTeqxXEw9HDyZIVt5U1myYICIHYDF4W/d5l2hQbcpjb5CXej3LIjQklPVo8SDBScZ5UOSuwGL2KdJ1pobXCZHL2VL6PoEGZJoDUZn9+QtqNEmX3tG8QuZJ5330XztClVc+Q51UesR7FJRE04w02+9B6nilnHkY/k8Hc2A39aOb5jbatKforpGmu7XrFswSvLaf//+9twwWfWo2eh/4X82LVZE7OCdlushJb0VuoJQoy4rcX5RoREywCgOWdJri5DrJ2WZMEjM0+4bAaynPBXuuolTXjZTeU+yFMWgZEKkYJV+F4sp1qonM6KlshPQ8kC8BaoYsjiTBicM+Y,iv:azs407Pu9U35jyxg35l5LhrNgWH/6LimCFFM+FFfPuo=,tag:RWaAzx8/WiyxkZSkLVexag==,type:str]
    known_hosts: ENC[AES256_GCM,data:GfCJuDYFo6rg83+mI3/INkZk8H3meU8lfVFvtRCgFp533GhYT/MWEV0TWaZBJVHP9UBjJf+D+kAvcO8oHCznsHQVfAN1EujlvqGqPMnn+rUvggzH7nTzv+VQxSM=,iv:jg6D3UmJ/wrcfgIlOqYsxrylTaS3BfRvkKInmwrFTU8=,tag:hgoCdSSKQs92bwdqcgDkCQ==,type:str]
sops:
    lastmodified: "2026-03-19T07:21:43Z"
    mac: ENC[AES256_GCM,data:fdx5dNXRgAgg9lYHRLmwjGzdiGu5KPPasJQUHJKbfK6l8K2AE7tTHXC2zuf8lIkH39qslg8L0Pbx6xWv1aF+b1Dx+rj95uaxLM0bxCj817ROoExXtoDgPsFJWBhIww0wZVxkKbAOn+e2GdXQfGD2n9/QE462IAMw5h0cQ3FUG38=,iv:VIJvOu7aWUrCVzLp5j2OH1VkWeKTSvkcZFHbEjiTgXg=,tag:GAfT9fgWXIvHi72yNQl15g==,type:str]
    pgp:
        - created_at: "2026-03-19T07:21:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+iIV7UXPYO1AQ/8Dh+h2fV/Ro0pDH5oXxZepJwVjpYnd+3/pLfL6arWwYYk
            ucJ83vUmbUc3mLS2qA/b3ZncFVouusOkoCWT7ZGrmfrKCGqZbthBlKqId/sQTJy2
            CHQARNHYd6fho0Zc+vAUKtR68MfcsOuF7AKbpybFOABvyAmbGi0yyzKUp5u1waC+
            kfZDUQBdcyuHqRPxNKDI9kalkfUeGiRRqP37vBqrc6xacwE7WOdMEGD5NDs2A6ip
            Z+a6dZIO4G+Ii7CsNt3UshbloAWBKolIkc9hn8uU1/L6qu+9f6uQ61Rv9xvNnuI6
            UN2PR1ZncrkGefxdFWMaiWSnKhlN4BYMjys9M4P2rKjIMcMP1DAvzOcgUb1yfw2V
            H9/snp1O6Dktxi7jOz1cpz4gc3IpJVx0FlZ+3nCf4Mto2xMQuemGvZtXOvcEntWR
            xKBrChZFZI5fR4RFIsgcdFWko8nFujc9Lpuu0JcO/TnnNC/E/rGNs2iiiZziO7pF
            H6EWZutzj78hM335hHAeLSpybuaQSJYgare46rTFV5cfLSdkvsWYEKfyVXPYFOo5
            /oJLhlQsz2WJCTri0NzNoqEqK298G+NPrb7JoPeju3uuOD3pWHGc/SJvUZzlMGcS
            9Urnzzc+fkemkobnw0yxUKThZR9vO8jWBDYbgp9ZMFPBD6fNPJ/m1TwSbHflM9TS
            XgFFuBFuSsJnoCHiYP6i/rP/BDKBDZDGMyMAnShjuchJ5cMlLH1VMAazbwmFk8kd
            GFsrYmlt3gTMwplyZbzNgq/dTJP+ShLRfuEd6dRYQyUZ913humj1ewRnidiIX8o=
            =nWsX
            -----END PGP MESSAGE-----
          fp: 76AF39813C2297E8F98C542D42436A07A9BA1DE0
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
