---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gha-clincha-values
  namespace: flux-system
data:
  values.yaml: |
    githubConfigUrl: "https://github.com/clincha-org"
    githubConfigSecret: "github-config-secret"
    minRunners: 3
    runnerGroup: "clincha-runners"
    runnerScaleSetName: "clincha-runners"