apiVersion: v1
kind: Namespace
metadata:
  name: hawkstore
---
apiVersion: v1
kind: Service
metadata:
  name: hawkstore
  namespace: hawkstore
spec:
  type: ExternalName
  externalName: 10.1.2.10
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hawkstore
  namespace: hawkstore
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.middlewares: hawkstore-hawkstore-sslheader@kubernetescrd
spec:
  tls:
    - secretName: hawkstore-certificate-secret
  rules:
    - host: hawkstore.clinch-home.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hawkstore
                port:
                  number: 80
    - host: hawkstore.clincha.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hawkstore
                port:
                  number: 80
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: hawkstore-sslheader
  namespace: hawkstore
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hawkstore-certificate
  namespace: hawkstore
spec:
  secretName: hawkstore-certificate-secret
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - hawkstore.clincha.co.uk
    - hawkstore.clinch-home.com