ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
ingressRoute:
  dashboard:
    enabled: true
    entryPoints: [web, websecure]
    matchRule: Host(`traefik.clinch-home.com`)
    tls:
      secretName: traefik-certificate-secret
providers:
  kubernetesIngress:
    allowExternalNameServices: true