---
- name: "Check if Helm is installed"
  ansible.builtin.command:
    cmd: "helm version"
  register: helm_version_check
  changed_when: false
  failed_when: false

- name: "Install Helm"
  when: helm_version_check.rc != 0
  block:
    - name: "Download Helm"
      ansible.builtin.get_url:
        url: "{{ helm_download_url }}"
        checksum: "{{ helm_checksum }}"
        dest: /tmp/
        mode: "0644"
      register: helm_download

    - name: "Decompress Helm"
      ansible.builtin.unarchive:
        remote_src: true
        src: "{{ helm_download.dest }}"
        dest: /tmp/
      register: helm_unarchive

    - name: "Move Helm binary to binary location"
      ansible.builtin.copy:
        remote_src: true
        src: "{{ helm_unarchive.dest }}/linux-amd64/helm"
        dest: /usr/bin/helm
        mode: "0755"
        owner: root
        group: root

- name: "Autocomplete helm"
  ansible.builtin.lineinfile:
    path: /home/kubernetes/.bashrc
    line: "source <(helm completion bash)"
    regexp: "^source <(helm completion bash)$"
    state: present
