---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: satisfactory
  namespace: flux-system
spec:
  interval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/flux/applications/hawkfield/satisfactory
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
