---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-certificate
  namespace: monitoring
spec:
  secretName: grafana-certificate-secret
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - grafana.clinch-home.com