apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-watchdog
    namespace: monitoring
type: Opaque
stringData:
    push-url: ENC[AES256_GCM,data:0xyGpViMu1k+z8CKMoemzWV+MJwV2rM/7xQj5DWlVrCddWWwD0vNaR0ooDb7X6LGL7OoB+hyVbPLNHxFaq3S4g==,iv:6N5XX9rImrLi6eyHdFM0SKrQOC5clW56rWJfhKoz3x8=,tag:JaHU2dk2XxXc366odPQ71g==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T15:04:25Z"
    mac: ENC[AES256_GCM,data:dCnyp//+qw4/kTrY2nWniNBP+c3hWfczc1UmdK+oTCJsv843JF72tCdTkqet5yT0d/jHa+2ibjwdewatdgrAYCwSsdUtJXJ/gFIL9+o75MvSgdxpU3OgS0iD5vzNlSVAvQs2VDiKEZuAxkjpvoaC1U4s9eVtyIo9jMCcqAfSB/A=,iv:X+DB155ZfevyE/y0vhsWtVDT+od/5fALjaPZa2WfGU0=,tag:TG60mY5pYJ8xMJ209QqbyA==,type:str]
    pgp:
        - created_at: "2026-08-07T15:04:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+iIV7UXPYO1AQ/+Ou8STxFiL7XoCfFi8SfQV9u10LDNuajA8EBHWoDfpPh5
            9tne2ZNkuMZwSNzGAE/ywgJQtKTy+bRVmxXvSEbge87knXqjHJ+4sR2SoT+K2BpL
            PPDsj1NWVrb94GHusyxq/0FaHIN5LEXvFSa7dT13CToFoZ06a5Jz5LePec8NRvsm
            VtmU58z7z0KmrsHhivmoF5+2BPOCXHxfMCKHnSuZlPM/5RTBIEI34B/Y01NItwGf
            VSsqFjGw0GUdfE0mSMU9KrOVFRduAW+1moBTmDbOXRbvo4Lx6wiKsGnqxwt+t+u2
            8MfF+udfbuxHL2CGismsSy0ypw7FTdLYhfeQyh7mmpfLyNokhP3KL4udCA4HhB8u
            d3Y3j0ePkqYnENatSq8xSvAh5qzpel7JC4Spdq8YHFpiPlR+ez/qSkTCYkotQPiP
            4x/2QaOx3zrEVE6F0J6hP05gWYEPdBEPh5SVEcxGgYcUkznRoDVHpltfPHKkWL66
            6bSpx4aGSmx8EXhkosvR597XonLFcqCb5pIDt7q+UOYzq5rYHhmMKPGgkB/mDmFp
            5dhyOXE952YL+mNk9xJMAM1RGrHOm10WFp77dkJyVgadCCq0cWElQSU/3rlSvt5W
            hzPOl6Lm5C9COF8KASwwZtN+XclyKI3Qk046q/E0TkXisrRbNH5pKL5NsECql0jS
            XAGv717CZ4iwACewnctBwTTCnWGE7lkEiG15sNMhMv1QKZmjBT5AT/uQvp0W/u1h
            6bIbriAGLdBUxN1302K9N67/1aNY3nX2p4sPmQsz421k3fSf9tcBwKOC7J5m
            =1bAq
            -----END PGP MESSAGE-----
          fp: 76AF39813C2297E8F98C542D42436A07A9BA1DE0
    version: 3.13.1
