fullnameOverride: alloy
namespaceOverride: monitoring
controller:
  type: daemonset
  hostPID: true
  volumes:
    extra:
      - name: host-root
        hostPath:
          path: /
          type: Directory
alloy:
  mounts:
    varlog: true
    extra:
      - name: host-root
        mountPath: /host/root
        readOnly: true
  extraEnv:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  configMap:
    create: false
    name: alloy-config
    key: config.alloy