apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:H55D/+TmaxZGqr0JeZQTUVkr,iv:+ErYUGFwFAdkSktSmESOZ7XkUwwX+MU9vvlbJa0ulbk=,tag:ngXspLYIu12cEIHAnabA+Q==,type:str]
    admin-user: ENC[AES256_GCM,data:d2PpaAMytA==,iv:lVq/9gijfdgT9FBHpK1hx2QK3cDjEmy4CxKY2V31orA=,tag:65p9/9tntIRF3MpHVq4rGA==,type:str]
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
sops:
    lastmodified: "2025-12-13T16:05:23Z"
    mac: ENC[AES256_GCM,data:jp1KjYSt0Rgh2LII9HMAg58JGh+ytSU4TNI6urXEhWsGv27tJe8CNwAaBWDtW6418RYMIOJjX7Y3ERrXZ2TqGW6ObNOvQAk6hK2otrTweNal5bMMYBwgnHDeZCO5MNMgoodkG7WHqFmVvnDC067WBW9FFRdxuVsRAM8u3MFO93Q=,iv:7IT22UIYQZQmaCHys6LcbIFu0LePnrOWueKet9ArqzU=,tag:E+v9SzigjA4MHU/Y2OaF5Q==,type:str]
    pgp:
        - created_at: "2025-12-13T16:05:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+iIV7UXPYO1AQ/+N8XiKsiDvQlbD62O7WnsoEmgyqgU178qek5IIXyRNIGH
            nFNkFajGG/viMn6z5rywXHtwSypf7wBGIpnUAnGNN22NjoqoZkt7YHNSl/J8YuN5
            /uv54M2yF2cb4nhS3OD2ATimhm/Dz9MtwPvSsZy2Aw6yDxaRkca7XgoIPY0I72wy
            2SL90PJXmQWnLJuIZHbIOqoCfoAMrihrq2evpz3S2cBd0cWbHnJTc6PpykQk/+vS
            Bo0DVfIsJgf29V+tGktL2V5GCYpGuyhXoiDkt7w/aa59FufQluMX2UNoKd0mAXK3
            ixKpNhuVk/aUeIg8bpswkcthzNsTWjIKDyDcHwMZYP0GP+0WsT7BwodLBYDY4/yT
            3uY8bJ5L0jQDuQCU0aJ8v7nO3xxfdyFLLabEue5g7hryHhYCymLtw0vxs6gpcHcx
            pVdcgbDA0WExsDRPxWsrwZzrluy3bDQJnhRUIAI2DSloqqEnEXFcKkYTNkb8CccI
            eYFBD0z6UUEYbKFzMK8QGZfmEe130gQfVIBMassQpNLco2dzTEMgaQa8DJGH3wIn
            7J2x3Ytlw9vSpnsaZHZriGUwFAXut9cg6+sqf6WxCI8a75f2ZDFtcfHw8BxRWiRb
            0PDr8jcXVlIG2GfacJSKZM3XnOlOfOSl9LGAX46SCt/A2IRzbJLT/0XXN2yRW1TS
            XAHP2eWF4/VVFZmNULPH02qDpIbXXuOr7dUNe0nFU3pxXaCN3H+re2oO96NvWdp+
            nWRWqRob6qOlWLiZkH/0CiRZVzD/fSMdaxEelgW/vEvaLZJ/ms3FUadj0Qbu
            =7xyH
            -----END PGP MESSAGE-----
          fp: 76AF39813C2297E8F98C542D42436A07A9BA1DE0
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
