apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
data:
    admin-user: ENC[AES256_GCM,data:/kgrs42mng==,iv:E0tqqgunFsJ0eLFtJATTKPOqOWPqJ83GH+A/IXg7DSU=,tag:6uLyAHcpFqvbzCR8Pdr5YQ==,type:str]
    admin-password: ENC[AES256_GCM,data:FhKb1iXmK89rcgceApr+uLs7,iv:Kt/Yzy1kBn3TWIx9Ex7a1I4aLYCoig3qcylbYU30uMI=,tag:bB0guXWmcVWio4FnvyBW4g==,type:str]
sops:
    lastmodified: "2025-12-13T16:26:31Z"
    mac: ENC[AES256_GCM,data:t3imUjjrNnyKlYOPmcR7bloSVakeF7Jj5VSnXXDU9U2XPFCrpgWjdTbO08DvCMtlD/2Zk9x7QIXM5eAidia/4bQQt4u0OC1A5UYFhkoO1YgS+p4SeDuU2+iY+aZ02MEeX0ye8QJMPw0yGYW2p4nQEdLwuM/uc4FuEZGJv1j34N4=,iv:EjAIhBWggACy7+m15nnsOPBsBCICQnW9e1Fhc8m/tw0=,tag:mNJqcDyrZURG09Wg4uPTGQ==,type:str]
    pgp:
        - created_at: "2025-12-13T16:26:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+iIV7UXPYO1AQ/+KsclwFkiJ5FrPEqSUGAF7IQDSWDYOKnBHz5HT4UiGPm/
            yW6AYjJ7lprhmi0cVBIl+a6VFxUz7B31S7KoE9jh6F9TZWqz7YdKQdaA8vUSllTz
            s9HyOcIbI9BxeHYJ/h7JK/9LYTDZ7dsy7H0sHUVu0Hsbb1oGprNA/nJteXjzhX9Q
            RZ+z+u3QK1y8NVpkAhT/mO10QFbVNsJRmov/KAtk1ekrR1Qrp6k68m5+yg+bttYn
            S2jUG+eYvluEgYaKGD18PYNhIOsW/aER2pg6q/H8ET0dZJ/lpz4nllEY8EJNwvyA
            wObL5JSfylvwp4l1d5N8qL3Sd+Q6A7JxGF7Z5Z50TX62THllMk0U22D4gm+GaJgs
            7cFlnpxkfYvxvlGzV1+i6WmK4BeiY9MJtmTrLdGeudPfdGqHI3J5jFZvpNBGHz2y
            JT9KnFGVedwNie/3Glkvb3UyjjsSAbjgvWTa9p48ptWrzxN7hoO96S4/t1eSPCo6
            oFLTxYZhI8dWCR6nLmfrayZ4hrraSK/b6OFKMMJa3ekLEI2jfVSy8NRwDUdaNSMr
            nU2laAp9mTtExZ6W7nS3ATb3EEbc1Z8eyx013wAEnLsUZeArBtKOih1utqcEQ/Pd
            GMxx2JJW2VCbiUAltGaihMA6Ewa9cmWwEmR6W5jLzpX3oDxhPqGbGITHD02W/rXS
            XgEp7SJpciWQqFvGJhPUXxQj9JGg/J6J4XMAKcxchk7F8e0se3KKVhTNEDSPvGWo
            tlR4Amv4eeq1tjdOnQHMTJlWC7JBzO6K9IkQK8pxipWnv6wCQWltLXBIlkdQMlc=
            =sq5b
            -----END PGP MESSAGE-----
          fp: 76AF39813C2297E8F98C542D42436A07A9BA1DE0
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
