apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:LmBo+5YCpQ==,iv:nASXAxYuX45X4U2QF1ROc8TVHDaSYY7QU2Ixaiwfz8o=,tag:FYcg4v5S1WTsuLu7govHrQ==,type:str]
    admin-password: ENC[AES256_GCM,data:iP1e8VtSQe9SYcOODTIRpFrd,iv:33m5X+aI2WSa1NDCTCIloaAsgYa00CqMXGobNErIHHE=,tag:E7nzulkjqIcoNUvHQlX4/Q==,type:str]
sops:
    lastmodified: "2025-12-13T16:32:40Z"
    mac: ENC[AES256_GCM,data:rYICaozQSrjqgHBb5hs2GvSVvbepTrhRm7/TciaUkHWZmaOYD9Fykau0++s/Z250xcAn2q6jW3xJlG7FVu1OqLGZEt4FPPa+1vK7l2W/5YcyA+QICwPYgPFZ12/D+T1pZBRyJ+kl4OwIxz1auC826q7N/AvNqTr6ViQejx7Y0GI=,iv:7YHbQfCZ1qt5NE/ghlJEdZ8CeeTOX0jZqETFdp3JZUM=,tag:u0GcygL/3Dzbn1Nr7To/HA==,type:str]
    pgp:
        - created_at: "2025-12-13T16:32:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+iIV7UXPYO1AQ//YPOPOyU2857c4ERqWCFABulL1XYmyfQ58md5Pj0MHuOD
            khhUx0pEbfVpuvNNiF8U6JzAdBreSkSszHxrNLxeux3AtYqqRkFifnsM5lmAC8K7
            SfAQBdGX9KKbPO65ndaHMZ6kfBclqx9xooOjF9UDNQOJ2jX/3fOcOwCGMGqHpyCS
            D9EwrnWtOkASV8ahnsmCtazQZOWB7+eWsGW3012PqaMOJu5mqt+3VSbA74NVG65i
            KkSN3vSuGi7CI5M/jJQzoSZCac21KeUOK/ggjvYbG6QnRsyscXVyI9A5YVZnG4N2
            jJjoSMrPXQ2ZPH/oEzXCt8o3bJv6S2W473/mHyfQkQ+l9hqgPE75lkjozOAV1t2n
            p2GEeEP2tY6Z3V0AWZaYr0m/pYFXw2iCi/OiXEVUD3O7Vr1wJSHPrBeUsREeecni
            vT6ntIW9kTYTFtRA7MC85S4JMcXQQEmuhyfZroDLTsN2Vkam10TEYtK1wl1nyt92
            mD9KNakYhhw69HDOZj/+yHg2p/MktKS2CrjTpWCQESrWUQv3iKz58p+KfK9tfTGR
            XqH/y7ObZdSOd02wjgYAzqomoGc/j+T11p8TDov1uwywZPQI4KnBor2asihvNueq
            egPxvPvQ1uT9B9LDt3DzR+m+vw4VKrSWIAAZkhxr8CuFol+6xBBJO358XDWUfV/S
            XgHqSbze4obRY66LQp2iuApUv0QpW2I2/n5Z7XC7xydWJe9IGCXud+MqPWgik78e
            1zojd4WrSHc0sUzeHQGDJsAObNdHhvu4cI05tVSrtk7TgyyCxhjJnb+4UHYMrNc=
            =44RB
            -----END PGP MESSAGE-----
          fp: 76AF39813C2297E8F98C542D42436A07A9BA1DE0
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
