apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring
resources:
  - ../../base/monitoring
configMapGenerator:
  - name: prometheus.yml
    namespace: monitoring
    files:
      - prometheus.yml
    options:
      disableNameSuffixHash: true
  - name: alloy-values
    namespace: monitoring
    files:
      - values.yml=alloy-values.yml
    options:
      disableNameSuffixHash: true
  - name: alloy-config
    namespace: monitoring
    files:
      - config.alloy
    options:
      disableNameSuffixHash: true
  - name: loki-values
    namespace: monitoring
    files:
      - values.yml=loki-values.yml
    options:
      disableNameSuffixHash: true