apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring
resources:
  - ../../base/monitoring
  - truenas-api-key.sops.yaml
  - loki-minio-creds.sops.yaml
configMapGenerator:
  - name: prometheus.yml
    namespace: monitoring
    files:
      - prometheus.yml
    options:
      disableNameSuffixHash: true
  - name: alloy-values
    namespace: monitoring
    files:
      - values.yml=alloy-values.yml
    options:
      disableNameSuffixHash: true
  - name: alloy-config
    namespace: monitoring
    files:
      - config.alloy
    options:
      disableNameSuffixHash: true
  - name: loki-values
    namespace: monitoring
    files:
      - values.yml=loki-values.yml
    options:
      disableNameSuffixHash: true
  - name: graphite-mapping
    namespace: monitoring
    files:
      - graphite_mapping.conf
    options:
      disableNameSuffixHash: true
  - name: alloy-syslog-config
    namespace: monitoring
    files:
      - config-syslog.alloy
    options:
      disableNameSuffixHash: true
  - name: truenas-exporter-script
    namespace: monitoring
    files:
      - truenas_exporter.py
    options:
      disableNameSuffixHash: true