apiVersion: v1
kind: Secret
metadata:
    name: unifi-poller-credentials
    namespace: monitoring
type: Opaque
stringData:
    bristol-password: ENC[AES256_GCM,data:QNBl7Fujw56yTOdOFdMy/0XD5Fq8Ewop,iv:fzNNvff3+WBqGDAFW6brYegvMVO/QG6CIpCoKpVvnj4=,tag:B1DMlEKCsNm61a/LSNfeLQ==,type:str]
    london-password: ENC[AES256_GCM,data:Zn3KCHZDfcHkHCsLQDIx6gsnja9yKiaY,iv:fGvwPZg7y4bG8zp5JQ6VjVfoLOQHjBbg/WTtM7NAcJM=,tag:3DhdqYryD4RYB6u+Z7DfSQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T07:22:47Z"
    mac: ENC[AES256_GCM,data:Bkce9yOwu6j+yWZjSJ8TxA2hQcrVM6I79Vi1jBmOC7tBxIQSQj8kRjtCYhP3ZLr+7kCn5zHQmnkks5PkDhPnYrFuLJepU9l/SmEIs5pbRrIPKqyt1Tx8c5/1Fpk2YO+xjFOoq/9MHa3Gr8RFi9GmOWOcOWLFKua/L9YRk19rkfw=,iv:i7ixnlBxj3X+WlOcU3h/bbxwwP+dP9zY8ZTua6ZN35g=,tag:wWF8VMNMsk8LkA5MLGOglA==,type:str]
    pgp:
        - created_at: "2026-08-10T07:22:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+iIV7UXPYO1ARAApg7Ab3uXr9sLMeKLy8aEvggdkx46MLw0wEy2YaGgFL1p
            65YuPw1i4e0Fv3whEs6QF+aoucvrV7fefe2MNuJps6msd7d30k7MsM+xYbQl647q
            4s/L90LbCrivdKzChCmGsthF4S0Ja7Ge66QuOvgjxNEhV+YOizIdln5BeFWFIVjh
            30Z1FUUSxOQsDCXQjQhZmCkgBtFnPIGuRk9NfZuM6A5jPTeI0T1GkgB8WPODwRvS
            0u/2c+QdXNMxNXl+uC5trfjDR5Dq69pBvLcuR8GZ6mavRjM59irGq7BburO1uAUT
            G7u8jQ5kEkgkxvUjIFIvqV+akloeCdyCx239SU90g0qJgriJCM56K4Ro3CsZy4nB
            8gZFKebNJg8D54pXdPM1dLaQt50ImJHnmSAYVb977Uw/SwJ+J7vNySfX32B6Khm0
            Gs9b12rwW1koovX/NjW9eGo2ukinJWsOZIajVX2bDlKj2suZCwVV8+jeyEt2UCi3
            63lH8nsKEM8TQlpktMtnRy9l8lnEPz8lzYWdGp24f++4vW+1ipZxG1wEV77HAbWB
            LozqqA9nkVkGozXj5Aq4kBhhqmejcopFGCaNrJTnKUNq1yT4OWbU+WmtHOJRg3Vl
            ChNUkfHzXKQHoYHebIEqgWu3hpxLXTsndmfUfFMwJFPeKORVvJwGeW4WRp4cD4jS
            XAGFaEetNyuVRuIgkkcajkQ+cdV7HG1j9N8+9vX7ExuX9RTLvSq0ZOe2+EpMITsS
            AFG6Tz8ut7/1pPmVzLh891OnnQ6QNJdeB7gym3+Sgll7wOKGtX3A2sc2mVw3
            =PuMq
            -----END PGP MESSAGE-----
          fp: 76AF39813C2297E8F98C542D42436A07A9BA1DE0
    version: 3.13.1
