---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gha-elasticstar-values
  namespace: gha-elasticstar
data:
  values.yaml: |
    githubConfigUrl: "https://github.com/clincha/ElasticStar"
    githubConfigSecret: "github-config-secret"
    minRunners: 1