---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: satisfactory-satisfactory-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "nfs"
  nfs:
    server: 10.1.2.10
    path: /mnt/data/satisfactory/2026/config
  claimRef:
    namespace: satisfactory
    name: satisfactory-satisfactory-config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: satisfactory-satisfactory-server-cache
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "nfs"
  nfs:
    server: 10.1.2.10
    path: /mnt/data/satisfactory/2026/server-cache
  claimRef:
    namespace: satisfactory
    name: satisfactory-satisfactory-server-cache
