- op: replace
  path: /metadata/name
  value: dev
- op: replace
  path: /metadata/annotations/node.longhorn.io~1create-default-disk # ~1 represents /
  value: |-
    [
      {
        "name": "fast",
        "path": "/var/lib/longhorn",
        "allowScheduling": true,
        "tags": [
          "fast"
        ]
      }
    ]