- op: replace
  path: /metadata/name
  value: dev-m02
- op: replace
  path: /metadata/annotations/node.longhorn.io~1default-disks-config # ~1 represents /
  value: |-
    [
      {
        "name": "fast",
        "path": "/tmp",
        "allowScheduling": true,
        "tags": [
          "fast"
        ]
      }
    ]