---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-controller-staging
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/flux/apps/staging/metallb/controller
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-configuration-staging
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/flux/apps/staging/metallb/configuration
  dependsOn:
    - name: metallb-controller-staging
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg