---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  ingressClassName: nginx
  tls:
    - secretName: uptime-kuma-certificate-secret
  rules:
    - host: status.clincha.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uptime-kuma-uptime-kuma
                port:
                  number: 3001
    - host: www.status.clincha.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uptime-kuma-uptime-kuma
                port:
                  number: 3001
    - host: status.clinch-home.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uptime-kuma-uptime-kuma
                port:
                  number: 3001
    - host: www.status.clinch-home.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uptime-kuma-uptime-kuma
                port:
                  number: 3001