---
apiVersion: v1
kind: ConfigMap
metadata:
  name: certificate-manager-values
  namespace: certificate-manager
data:
  values.yaml: |
    crds:
      enabled: true
    extraArgs:
      - --dns01-recursive-nameservers-only
      - --dns01-recursive-nameservers=1.1.1.1:53,1.0.0.1:53