---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: deliver
  namespace: flux-system
spec:
  interval: 5m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: deliver
  path: ./deploy
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
