apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:L83jiRrEJ7f4VkO1+gvEnZbBYKSclXqP6fXtgg==,iv:peFaFkgL/Y+nrO+gf3vuwNHWbouVPXo2xwLK4OO94gk=,tag:dGy7ZzWlT4thR/YH/7VrxA==,type:str]
    admin-user: ENC[AES256_GCM,data:CVE0ftWsio4l+2ZS,iv:U0cOLxEC1qSwEhHracW6JJzr1fboslo0TfTbmAqyf8Q=,tag:RzOYkrSQuMCRgmLtbjEwsg==,type:str]
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
sops:
    lastmodified: "2025-09-20T20:18:32Z"
    mac: ENC[AES256_GCM,data:he7xb5iTh/rjLfVDtSWCJ1+f97vN0yLesEtf4/snJ8hvzjGu3kmz5Wy/qKj49KStgTS0XR6SgXydYV4DJyXtynUqYfhSkr3QiMN2QqcJwPiMHwB0RN2qdHAAZbVlGOjhHriI6ArDBOpDwLcJnBfqIjW06mRgO3Em20zmdqhcVx0=,iv:4ZcNCCWdXr3DYm7Qu3aTPnOdyQlQ39Fay9NAUENdP/Y=,tag:xQ2SDF+2MJbTtDAU1l8rPw==,type:str]
    pgp:
        - created_at: "2025-09-20T20:18:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+iIV7UXPYO1AQ/8Dh3AooJ4V6OiblTbqi3NpK81CPhP6HbTLRPJ8WWS1phY
            35J9RoNJP6b/Vfi6lB/GNZzUhh0pgQl7ynzKFhy2NzsVzLamxjtl4pido4gr8yNp
            LxMgp3PxmCQk3vi/LHOtNCkycL8APZ9Knz1ofNJs0DGCZ4LeIdT6W4f4yo4vTXeT
            33gfuByCfOHwHs+XbA0hWQuImeNU9O+wOnUlnLCa/nCgvfP1UorpSxSa+bPPAwjx
            wH/dTaahJH/scniNNgN9uSQtxNPIPwMySjK9wS66RWDrtxfiIGVtJhLm7XvWj5x1
            Y07LUw0umV0Yndz8czaAtPCm9XHOVjg/qE4XktuYV+/pm3IAwj0/z0BwrfYRamt0
            oQ6tfZDBykprrxWxpm/we+v+HrMRDcpJXWGTXVePD1B3gwW64jdN+jcmUqaUbCj6
            gFaBsuaNglwG5hc6kdoTHRf8C9ZmiOooKCDvcrgJ9rRrIoaBujCb5We7SYY8cQGT
            ZgWBFh6Sx+AGGVeLxvJaoqjl+e++V4xuZl513MzyvRM5KPD3xPg9fGxoWAsQbFNH
            K5e4ADk0jLq0rLbmdbmgiDy4W84fALs4HPKVl3Toj+5HlYQlggsSVqOF/6VLzPXf
            k+3KcOeDMwwyFZivmi+dDuBUHCg5B2l3ZbxKX8bzBkSdyQvWAm8jo0F1jSzFy8/S
            XgHOXF/AmEhoKMskNkYnut3h1vxU3etOTX0FV+Jeqgq6LaYZybw+9j5jHU6oi+uc
            uFIfL1IoC58Rt7ttT1k+NyRMi7lZ7xQ/ueApiBIhwUfTVkQl2ByBHF189qkCVrc=
            =l3lf
            -----END PGP MESSAGE-----
          fp: 76AF39813C2297E8F98C542D42436A07A9BA1DE0
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
