---
ansible_user: root
ansible_ssh_pass: null

adguard_local_dns_entries:
  - domain: "hawk01.clinch-home.com"
    answer: "10.1.2.11"
  - domain: "hawk02.clinch-home.com"
    answer: "10.1.2.12"
  - domain: "hawk03.clinch-home.com"
    answer: "10.1.2.13"
  - domain: "lon01.clinch-home.com"
    answer: "10.2.2.11"
  - domain: "dns-hawk-1.clinch-home.com"
    answer: "10.1.2.131"
  - domain: "dns-lon-1.clinch-home.com"
    answer: "10.2.2.131"
  - domain: "sonarr.clinch-home.com"
    answer: "10.1.2.101"
  - domain: "radarr.clinch-home.com"
    answer: "10.1.2.101"
  - domain: "bazarr.clinch-home.com"
    answer: "10.1.2.101"
  - domain: "sabnzbd.clinch-home.com"
    answer: "10.1.2.101"
  - domain: "plex.clinch-home.com"
    answer: "10.1.2.101"
  - domain: "plex.clinch-home.com"
    answer: "10.1.2.101"
