---
ansible_user: root
ansible_ssh_pass: null

adguard_dns_rewrites:
  - domain: "hawk01.clinch-home.com"
    answer: "10.1.2.11"
  - domain: "hawk02.clinch-home.com"
    answer: "10.1.2.12"
  - domain: "hawk03.clinch-home.com"
    answer: "10.1.2.13"
  - domain: "lon01.clinch-home.com"
    answer: "10.2.2.11"
  - domain: "dns-hawk-1.clinch-home.com"
    answer: "10.1.2.131"
  - domain: "dns-lon-1.clinch-home.com"
    answer: "10.2.2.131"
