cluster_name: "london"
dns_domain: "clinch-home.com"

user_list:
  - {
    name: "ansible",
    uid: "1000",
    gid: "1000",
    shell: "/bin/bash",
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL0PsOw/7B9Qr16/iKa2h3j5Nr0jZtrj+JI8qKgYSWep ansible"
  }
  - {
    name: "clincha",
    uid: "1001",
    gid: "1001",
    shell: "/bin/bash",
    key: "https://github.com/clincha.keys"
  }
