---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: actions-runner-controller-charts
  namespace: gha-controller
spec:
  interval: 30m
  type: oci
  url: oci://ghcr.io/actions/actions-runner-controller-charts