apiVersion: v1
kind: Secret
metadata:
    name: secret-basic-auth
    namespace: elastic-finance
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:GE0veqzWGA==,iv:ziaKx1wuxkfiI9QIdyrlUO7yfxR9GJ+SQjzAoLO27X0=,tag:FqonAT/SVMElJFp+Az3utA==,type:str]
    password: ENC[AES256_GCM,data:NPJ5Z2NiEbdvjGL6dDa39OXokLE=,iv:6rqNIbOC7n/GM1lOFYMbRKpbdrIQH4IusgoOXNnrY4I=,tag:OEvj7KC/gaklXhsGlgL8AA==,type:str]
    roles: ENC[AES256_GCM,data:yiA6JyBUs0uM,iv:L1XQg5DKnrGUYJ3rLZ2UrzAyuFWJZ6wueZfhQVAuHk4=,tag:Q6hZTHudWaKrhNypXgmzSg==,type:str]
sops:
    lastmodified: "2025-10-21T18:33:03Z"
    mac: ENC[AES256_GCM,data:0UESaWVQ7geHzKrgY9ALeUuRdjfdK2EKL0xLKHzkv6XDljYiKoSaCCzCIXFWI0k2/O6k2g6yomAGYGzEpJhaFUprv/nwNznXkmbo14QYJhc+Ae86QD7iGDIp+RwZQW4cV5nMxF8S/kCcq33qYGaXp2Axwc44qHxy580boyIYcW4=,iv:NmRPLo+idtkKOCsdV2opDfK30FGXo4DvrwV/KyywwlU=,tag:3yjX7alOJy43pfIq7iayDQ==,type:str]
    pgp:
        - created_at: "2025-10-21T18:33:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+iIV7UXPYO1ARAAwTPmCqY3yv4yrRv4AosUQSvehJAN6tbTh0/j4badcbVV
            JiurmNRKaf8uOLo0xHdU6cef4M2kW+8a1KYUoVA4AJHznW+xODY+5usUrNJumats
            1tawdQYwX/fxCkivka25Kr/PmgFPAWJHV2p+y5fJPBFrcqc7At5iEutQMa1lA7lo
            qq5NBsooHoeyg/Gfelyojchn3vud76OBO8mNeuYsfm2Dy+elQYrb5bGx9C+cNOtE
            Nom1Q/5RSSoeaYPS9I5AOHYDj+dGjvCTs/vehZ8ztIFY30bLDmIbFXHsO+vCiXjR
            L0LxHrBVhNukZfof1wEHMxv3lbeHvRB+IK6EEnmT7AULKiAfiAOuhzrC1qBds1OF
            xnpJ28oIE6soNgLAEdjb5Z0CTVD/Ha0oYc6qaAvo3m9yZvWNY/XULZpqGgO0tbd1
            cO9LARKM6q/So+tg8N7t5d9YMlWTJKtdUglME8u+kPD1gcx1W/XwN9Mx2t5XHoh+
            ALT+34z9R/FITMiOBGMrn0qFq3HglFq33mGwfalL/m8Q8m6MlgnSeyvuw+P6y7p8
            LxEb69JyaFSrcZxojVChdgYRELbQGo5ltsWC9UijFpUkmTQkS3P6yTYFwjq02xJ8
            X2Elwbd2nbpUaSJ4GoeR3PecMrfS4koJ7XooqCGk89y9n/ZYkT7FXlWpaaolLhbS
            XgHeXzHmh1ixZLTCsOvWGp4ax8tvUU9mVLmy0kCKSoBE/IekyUBN6Fw4XBKzeKvo
            78sVWnSx+AuiNT6VVKIqHXJKxWJRGg/SvUsoxnlBX1QVe6vEWm0HlzQ0vpr5ALI=
            =E5Sy
            -----END PGP MESSAGE-----
          fp: 76AF39813C2297E8F98C542D42436A07A9BA1DE0
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
