service:
  annotations:
    metallb.io/loadBalancerIPs: 10.2.0.60
ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
ingressRoute:
  dashboard:
    enabled: true
    entryPoints: [ web, websecure ]
    matchRule: Host(`traefik.dev.clinch-home.com`)
    tls:
      secretName: traefik-certificate-secret
providers:
  kubernetesIngress:
    allowExternalNameServices: true