---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: production
  namespace: metallb
spec:
  addresses:
    - 10.1.2.200-10.1.2.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: production
  namespace: metallb
spec:
  ipAddressPools:
    - production
