---
apiVersion: v1
kind: Namespace
metadata:
  name: github-runners-clincha
  labels:
    name: github-runners-clincha
---
apiVersion: v1
kind: Secret
metadata:
  name: github-config-secret
  namespace: github-runners-clincha
type: Opaque
stringData:
  github_app_id: ""
  github_app_installation_id: ""
data:
  github_app_private_key: ""
