---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elastic-certificate
  namespace: elastic-finance
spec:
  secretName: elastic-certificate-secret
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - elastic.dev.clincha.co.uk
    - elastic.dev.clinch-home.com