apiVersion: v1
kind: Secret
metadata:
    name: giftlist-smtp
    namespace: giftlist
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:DPpuB23VB6mI6qXsbDIyQw==,iv:nkSwyQtqqkj9M1o5FKe1bjsyEL/XDGC0rvjOtQf6iA0=,tag:c0RZX4gpv6DFDV7bZfX5Nw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T20:19:22Z"
    mac: ENC[AES256_GCM,data:prmbG5L6Wb8UjwwhmrMnvFNxVOtXiutdB8bwmZWvYP3cAvwJU8ZuGG5pqwhm0gI9DIxAWgp9mS1hyZHmp9VrIbYO7/klFN9ZTbl6VRvc656BLUDMeBywHCqXKgxbjH/CP5MdBZycHXYyNm8sJuU5kU3sqIBz8/jlLFzfTSJaYNw=,iv:6vehzCQFu3XFiCLd0a3yqOuTLnkSxRLENBvXzpqm4dE=,tag:KRktmMugxjS5CWNLU0BcNA==,type:str]
    pgp:
        - created_at: "2026-08-19T20:19:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+iIV7UXPYO1ARAAgAe4/biI6rjrSnxMXq4PKUVTyFehVoZ3aiF2D+iqEv2S
            bX0HKIQyxmQ16CS7wO8IZsmDd7TJiBKenCCb8LwBOjh5NXmCL94Nz5exmo0q7qb3
            Pk9pCNY96S/K5sMQAyqqD9Oes5IyCTkoncMrw1QkcuoZdWyijRv5MWaDUVopbCYX
            yIagTfdNaBEdAfSjU8H/zHjaFOBQQlBKFn7AgvZQEOhvDH3IJYRzCzPFipWC6xkg
            G02jnJLQsRweMxR7qVRjYuDE54FV1mJht3UopMlX3Xe7zYS0WOFCA0F4iM9VGnvk
            tdEoF9m5vUJ0p7GsrPmBZjOY2Jb1ogvUBfgc2+FEvHZ2fi1757N2/lljFFkGUtmF
            +bRlqacp8rMrwKgjkpJ2b3oFSCCSXqN9KX2gL5DhwdbcyHOGCkyKsowb7EGkQcDi
            78jFQAl36/l8CleJD5tdRv8l1uzkeS1gBBizjMbhb/5hpi1rplUNWCZli9Skg6W4
            w25wJ6UeBZI8+YyV/orC9EFxjJMqFn567VlN+WIxw9JaHMLwLrXhTc5Iao/U/Dqu
            JEXc4ep/z3SjVqfU/O5FD5jcUXUDVoA6vnpkfeeBmmsV8Y8q4BtYq5y2/na65iEw
            KHmEmYVlPz1FOxDy7pC9B6Wpl4o+MkwhnNwpPlBh/aYTZOcJKiYytypaQ1F9k8/S
            XgFePsgruEAxsbJXxfNyqrHvyrwqM6pvCx186dtJtoqzXe+0mgAM6pBNHCNvKDB7
            Tt3BdbEeabeUMqoSde3QgYffBYQO5zpijmbrGFHRECGuNwQjxyCpRcJCyOzhst4=
            =U4RB
            -----END PGP MESSAGE-----
          fp: 76AF39813C2297E8F98C542D42436A07A9BA1DE0
    version: 3.13.1
