apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - serviceaccount.yml
  - giftlist-smtp.sops.yaml
  - giftlist-ghcr.sops.yaml
  - deployment.yml
  - service.yml
  - ingress.yml
  - certificate.yml
  - network-policy.yml
