---
- name: Set Pi-hole admin password
  ansible.builtin.command:
    cmd: pihole setpassword {{ pihole_admin_password }}
  changed_when: true
  no_log: true
  when: pihole_admin_password | length > 0

- name: Ensure pihole-FTL service is enabled and started
  ansible.builtin.systemd:
    name: pihole-FTL
    enabled: true
    state: started
