---
- name: Query existing custom DNS records
  ansible.builtin.command:
    cmd: pihole dns list
  register: pihole_dns_list
  changed_when: false

- name: Add custom DNS records
  ansible.builtin.command:
    cmd: pihole dns add {{ item.hostname }} {{ item.ip }}
  loop: "{{ pihole_dns_records }}"
  when: item.hostname not in pihole_dns_list.stdout
  changed_when: true
