apiVersion: v1
kind: Secret
metadata:
    name: nebula-sync-secrets
    namespace: nebula-sync
stringData:
    primary-password: ENC[AES256_GCM,data:1m7scmmELnQgsKnJgOqO01xJW3hGziUVX7RFWuBe+wY=,iv:SV0TarOVIKCxDW3Idyr6AqJXB1AyM6sKKGeIP1XEcG8=,tag:ukggWyHRLXT5KA6+FPdNqQ==,type:str]
    replica-1-password: ENC[AES256_GCM,data:Vm+MpB9VFHxkcQpW1Ns9n6n03IOAdwCm/hPvqUjP+xY=,iv:fverrNdVoBP+0bnzP15krjxOxVJi9REZnaCSs1M8gwc=,tag:WyxX1k4oTGJ/1+iFygck2w==,type:str]
sops:
    lastmodified: "2026-03-30T05:54:01Z"
    mac: ENC[AES256_GCM,data:SOJRifhv8Wz6HlvCnQ4ssBCfKbCbVhDg9mXsKrZ+AfhAP42oEUNfaupMQWHTOGDsW+z7pZkIdHKJJhbk1GT1q2BDI0Qw231eO+alRXpB0dll2GD2PNxIhycqooGt+mKvkpKX7L+FFNR62HN+gG1IyQ7rdFn9I3CZQBFMqKI1RR4=,iv:mTlOyN5si6mjodrmEdNUDZlvU7DEO62vMvnjVUDgUns=,tag:32jjVxlkTnNvziUTkBXsjw==,type:str]
    pgp:
        - created_at: "2026-03-30T05:54:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+iIV7UXPYO1AQ//Q6x2MUBCy/w8sL6klEju1CXj/VGe5/R9LcXXLYrc3Xhx
            wtXnvCNg32jBvk/aFzO6sg4BUnowFWhvPjYsVIrbHkfuxellGemPAHA5HSpIYKks
            +16f9nsl8wlTgT+6QJg3wU3NLt7O8Hn2jZ5GIVYVUlN7SWKnXdeJtTwcluqo/LSn
            W7oiHMeRiIwDp6tcoWIFQs2o082kIuHIybTvTI9uMKTLmJkzuPEgRvSSD3GKmx6V
            26PB42VuGBg1qF8UKpm6JctVBPhCq81snUejOpKWA65mTavAjQYn5JqhIco4KipL
            n2E0ng7XCk5SsZ/48Eed2cAq+xENqg9m0GjBlYP7OoHZF2dey3F/bcMkoGyPyiET
            5yixmw+zS+U6hJpuJIrxenjbbTxchHXH/EYlsMizJMuSrbC6lzktIXSHQ9fZUEhl
            y6i8jcoLkaU+Vfrr4I1D8/1rcjpEzVONjD0t04MU/rrlUNZ1C5moLop5meu3JRMj
            GQz2mDjms7SpyjYGMuz5XoerTlDCDs6ac0J4sAuLRmplWzKWmZhNSHLXo/Ikv/HI
            vnm1IcXUrkhSAf6mZeGh/V6MFUio69EQ3cNIgeFEbT9U3vwqNc0hpxsyG+MH9vVP
            Ldx/3CS9euMuxgoQJ1wQuhqfyjLT9Jq/E8cq1hb4od0fYthftMS1v4CaXqVPksnS
            XgHmKl0vhIkMdrKOJfBRysVvJES+GhwHTHx/6n5O9GtuuugbCGrFlw2ia4ljvOhc
            z1kdMcReksNqXI47GwWloOYlHlmgJCXeY/+ejX0FqXRZrEXwmqIcHKl4/qiCX+c=
            =PRAl
            -----END PGP MESSAGE-----
          fp: 76AF39813C2297E8F98C542D42436A07A9BA1DE0
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
