apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: github-actions-runner-controller-dev
resources:
  - ../../../base/github-actions-runner/configuration/clincha
  - ../../../base/github-actions-runner/configuration/elasticstar
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: runners-clincha
      namespace: flux-system
    path: helm-release-patch.yml