---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gha-clincha-values
  namespace: gha-clincha
data:
  values.yaml: |
    githubConfigUrl: "https://github.com/clincha-org"
    githubConfigSecret: "github-config-secret"
    minRunners: 3