---
- name: "Install sudo"
  ansible.builtin.apt:
    name: sudo
    state: present
    update_cache: true

- name: "Sudoers configuration"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/sudoers.d/{{ item | basename }}"
    validate: "visudo -cf %s"
    mode: "0440"
  loop: "{{ lookup('fileglob', 'files/*', wantlist=True) }}"
