---
- name: Apply base configuration
  hosts: base
  become: true
  roles:
    - role: users
    - role: sudoers
    - role: base

- name: Apply Kubernetes secondary disk configuration
  hosts: kube_node
  become: true
  vars:
    disks:
      - device: "/dev/vdb"
        vg: "fast"
        lv: "fast"
        mountpoint: "/mnt/fast"
  tasks:
    - name: Create partition
      community.general.parted:
        device: "{{ item.device }}"
        number: 1
        flags:
          - "lvm"
        label: gpt
        state: present
      loop: "{{ disks }}"

    - name: Create the volume group
      community.general.lvg:
        vg: "{{ item.vg }}"
        pvs: "{{ item.device }}1" # /dev/sdx1
      loop: "{{ disks }}"

    - name: Create the logical volume
      community.general.lvol:
        vg: "{{ item.vg }}"
        lv: "{{ item.lv }}"
        size: "100%VG"
      loop: "{{ disks }}"

    - name: Format the filesystem
      community.general.filesystem:
        fstype: xfs
        dev: "/dev/{{ item.vg }}/{{ item.lv }}"
      loop: "{{ disks }}"

    - name: Mount the disks
      ansible.posix.mount:
        path: "{{ item.mountpoint }}"
        src: "/dev/{{ item.vg }}/{{ item.lv }}"
        fstype: xfs
        state: mounted
      loop: "{{ disks }}"

- name: "Setup servers for Longhorn"
  hosts: kube_node
  become: true
  tasks:
    - name: "Install NFS Common"
      ansible.builtin.package:
        name: nfs-common
        state: present

    - name: "Disable multipath service"
      ansible.builtin.systemd:
        name: multipathd
        enabled: false
        state: stopped

    - name: "Enable dm_crypt kernel module"
      community.general.modprobe:
        name: dm_crypt
        state: present
        persistent: present

- name: "Create cluster"
  ansible.builtin.import_playbook: kubernetes_sigs.kubespray.cluster
  vars:
    kube_version: "1.33.5"
    cluster_name: "hawkfield"
    dns_domain: "hawkfield.clinch-home.com"

- name: "Configure kubernetes user"
  hosts: kube_control_plane
  tasks:
    - name: "Ensure .kube directory exists"
      ansible.builtin.file:
        path: "/home/kubernetes/.kube"
        state: directory
        mode: "0770"
        owner: "kubernetes"
        group: "kubernetes"

    - name: "Symlink kubectl admin.conf to /home/kubernetes/.kube/conf"
      ansible.builtin.file:
        src: /etc/kubernetes/admin.conf
        dest: /home/kubernetes/.kube/config
        state: link
        owner: "kubernetes"
        group: "kubernetes"

    - name: "Alias k"
      ansible.builtin.lineinfile:
        path: /home/kubernetes/.bashrc
        line: "alias k=kubectl"
        regexp: "^alias k=kubectl$"
        state: present

    - name: "Autocomplete kubectl"
      ansible.builtin.lineinfile:
        path: /home/kubernetes/.bashrc
        line: "source <(kubectl completion bash)"
        regexp: "^source <(kubectl completion bash)$"
        state: present

    - name: "Autocomplete k"
      ansible.builtin.lineinfile:
        path: /home/kubernetes/.bashrc
        line: "complete -o default -F __start_kubectl k"
        regexp: "^complete -o default -F __start_kubectl k$"
        state: present

    - name: "Install Flux"
      ansible.builtin.unarchive:
        src: "https://github.com/fluxcd/flux2/releases/download/v{{ flux_version }}/flux_{{ flux_version }}_linux_amd64.tar.gz"
        dest: "/usr/local/bin"
        extra_opts:
          - flux
        remote_src: true
        owner: "kubernetes"
        group: "kubernetes"
        mode: "0775"

    - name: "Autocomplete flux"
      ansible.builtin.lineinfile:
        path: /home/kubernetes/.bashrc
        line: "source <(flux completion bash)"
        regexp: "^source <(flux completion bash)$"
        state: present

- name: "Install Helm"
  hosts: kube_control_plane
  become: true
  roles:
    - role: helm

- name: "Configure kube-proxy strictARP"
  hosts: kube_control_plane
  become: true
  run_once: true
  tasks:
    - name: "Enable strictARP in kube-proxy configmap"
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          kubectl get configmap kube-proxy -n kube-system -o yaml | \
          sed 's/strictARP: false/strictARP: true/' | \
          kubectl apply -f -
        executable: /bin/bash
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      changed_when: true

- name: "Bootstrap Flux"
  hosts: kube_control_plane
  become: true
  tasks:
    - name: "Deploy SOPS GPG key for Flux"
      ansible.builtin.copy:
        dest: /home/kubernetes/flux-sops.asc
        content: "{{ flux_gpg_key }}"
        mode: "0600"
        owner: kubernetes
        group: kubernetes

    - name: "Install Kubernetes Python"
      ansible.builtin.package:
        name: python3-kubernetes
        state: present

    - name: "Create flux-system namespace"
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: flux-system
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      run_once: true

    - name: "Create SOPS Kubernetes secret"
      kubernetes.core.k8s:
        state: present
        namespace: flux-system
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: sops-gpg
          data:
            sops.asc: "{{ flux_gpg_key | b64encode }}"
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      run_once: true

    - name: "Ensure .ssh directory exists for kubernetes user"
      ansible.builtin.file:
        path: /home/kubernetes/.ssh
        state: directory
        mode: "0700"
        owner: kubernetes
        group: kubernetes

    - name: "Copy Flux SSH private key"
      ansible.builtin.copy:
        dest: /home/kubernetes/.ssh/flux
        content: "{{ flux_private_key }}"
        mode: "0600"
        owner: kubernetes
        group: kubernetes

    - name: "Bootstrap Flux to the cluster"
      ansible.builtin.shell: |
        flux bootstrap git --silent \
        --url=ssh://git@github.com/clincha-org/clincha \
        --branch=master \
        --private-key-file=/home/kubernetes/.ssh/flux \
        --path=kubernetes/flux/clusters/hawkfield \
        --cluster-domain='hawkfield.clinch-home.com' \
        --timeout=15m
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      run_once: true
      changed_when: true
