- name: "Proxmox host configuration"
  hosts: hawkfield
  become: true
  roles:
    - role: users
    - role: sudoers
  tasks:
    - name: "Install sudo"
      package:
        name: sudo
        state: present

    - name: "Ensure Ubuntu iso is available"
      ansible.builtin.get_url:
        url: "https://releases.ubuntu.com/24.04/ubuntu-24.04.2-live-server-amd64.iso"
        dest: "/var/lib/vz/template/iso/ubuntu.iso"
        checksum: "sha256:d6dab0c3a657988501b4bd76f1297c053df710e06e0c3aece60dead24f270b4d"
        owner: root
        group: root
        mode: 0644
