- name: "Proxmox host configuration"
  hosts: hawkfield
  become: true
  tasks:
    - name: "Install sudo"
      package:
        name: sudo
        state: present

    - name: "Ensure Ubuntu iso is available"
      ansible.builtin.get_url:
        url: "https://releases.ubuntu.com/24.04.1/ubuntu-24.04.1-live-server-amd64.iso"
        dest: "/var/lib/vz/template/iso/ubuntu-24.04.1-live-server-amd64.iso"
        checksum: "sha256:e240e4b801f7bb68c20d1356b60968ad0c33a41d00d828e74ceb3364a0317be9"
        owner: root
        group: root
        mode: 0644
  roles:
    - role: users
    - role: sudoers