- name: "Update packages"
  hosts: all
  become: true
  tasks:
    - name: "Update packages"
      ansible.builtin.package:
        name: "*"
        state: latest

#    - name: "Restart host"
#      ansible.builtin.reboot: