- name: "Update packages"
  hosts: all
  become: true
  tasks:
    - name: "Drain node"
      kubernetes.core.k8s_drain:
        name: "{{ inventory_hostname }}"
        state: drain
        delete_options:
          ignore_daemonsets: true
          delete_emptydir_data: true

    - name: "Update packages"
      ansible.builtin.package:
        name: "*"
        state: latest

    - name: "Check if reboot file is present"
      ansible.builtin.stat:
        path: "/var/run/reboot-required"

    - name: "Restart host"
      ansible.builtin.reboot:
        msg: "Rebooting after package update"
      when: stat.exists

    - name: "Uncordon node"
      kubernetes.core.k8s_drain:
        name: "{{ inventory_hostname }}"
        state: uncordon