- name: "Update packages"
  hosts: proxmox_nodes
  become: true
  tasks:
    - name: "Update packages"
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: true
        only_upgrade: true