---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-certificate
  namespace: monitoring
spec:
  secretName: prometheus-certificate-secret
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - prometheus.clinch-home.com
    - prometheus.clincha.co.uk
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-certificate
  namespace: monitoring
spec:
  secretName: grafana-certificate-secret
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - grafana.clinch-home.com
    - grafana.clincha.co.uk
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alloy-certificate
  namespace: monitoring
spec:
  secretName: alloy-certificate-secret
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - alloy.clinch-home.com
    - alloy.clincha.co.uk
