apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - helm-repository.yml
  - helm-release-alloy.yml
  - node_exporter.yml
  - prometheus.yml
  - certificate.yml
  - ingress.yml