apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - helm-repository.yml
  - helm-release-loki.yml
  - helm-release-alloy.yml
  - kube-state-metrics.yml
  - graphite-exporter.yml
  - alloy-syslog.yml
  - truenas-api-exporter.yml
  - prometheus.yml
  - grafana.yml
  - certificate.yml
  - ingress.yml