apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: longhorn-controller
resources:
  - ../../../base/longhorn/controller
patches:
  - target:
      kind: Node
      version: v1
      name: k8s-hawk-1
    path: node-01-patch.yml
  - target:
      kind: Node
      version: v1
      name: k8s-hawk-2
    path: node-02-patch.yml
  - target:
      kind: Node
      version: v1
      name: k8s-hawk-3
    path: node-03-patch.yml
  - target:
      kind: Ingress
      group: networking.k8s.io
      version: v1
      name: longhorn
      namespace: longhorn
    path: ingress-patch.yml
  - target:
      kind: Certificate
      group: cert-manager.io
      version: v1
      name: longhorn-certificate
      namespace: longhorn
    path: certificate-patch.yml
configMapGenerator:
  - namespace: longhorn
    name: longhorn-values
    files:
      - values.yml
    options:
      disableNameSuffixHash: true