apiVersion: v1
kind: Secret
metadata:
    name: uptime-kuma-admin-credentials
    namespace: uptime-kuma
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:V6+uutFbUQ==,iv:FIhJBgiuyq5ANOGkKdxqD9NcqKRSP3NpzvVKEAk19Ao=,tag:LjdK88C9PqGMv4VbsQRNrg==,type:str]
    password: ENC[AES256_GCM,data:3YbmLZhXKolN025FgjuzJE8igDWyFr3z8vuoyD8jufs=,iv:8M+c1lPbOKHG8SpRnV81FHUkBR+DcsEcOtZUzRP2/3g=,tag:29IHb/2on48AxYgAbmn3Qw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-02T17:36:34Z"
    mac: ENC[AES256_GCM,data:xYPtwuva2t4FYamw+hhMq6tRNlahmFueK5vqoNXjm45ox5Ytn+5ayj+iHZ9k8+cB8vhWFQsIKgj4JNJIqTSsQJoEP01XkOh0nsnIrsQH/g1PphJejWgonGZJXxpfFXpmddKVxRqr/GWz/D3srAm46lUZkd25I5mLBq3ZjAdgMxc=,iv:tG/GDEELiLy8VlTZ9Zgzvt7BmrzZtQT2uux1T4DmZgU=,tag:Mh4IPR32Iwv8yN2d0H852Q==,type:str]
    pgp:
        - created_at: "2026-08-02T17:36:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+iIV7UXPYO1AQ//RZO+A2o6/I8gFjl5PneGPmoOhEIxQ0hPQc6NpWvqhKSo
            FH0zGld8Fg00q+g+sDzTJsASXYeAOm1zlLNUc2IDZ9u1UiesypWWc/W/0XmUpI23
            HfBmYgO0/6TG0oGokl3GKaGN5+TmQW81YZ7yo8rnmugnCbFEnvGfPMuP+q+kyFEC
            s/mzYEg0F2jRSL/SBQ2/liSVCLOrAdaSZuUQHxpI/YKBAbNrMTdl6uvyYGFByVn+
            GKNawDvDAT0J+iFfzQc+MkevvrMpUaGcf9Fr+rKGsue4/jvoCZ9oxN8FzU2sw/cT
            41xi7Nh/B3CcxERGaUMSdId5mu9wOLQR1ol3eshcv2k5PM0JdC1jNMXqtW6DgGJp
            KNh6c8grCJEgNBqkOGbyKOr02rjwo6BFiQVsqkv2AarCea/dwfBCgOEiEcbeQTJu
            JpZxey9vP9MFHOwcNRgxu2Ure9i69weY4kCOt2CYGkjG7ccmnj7NBR5lmtWCrNI5
            5fGcetRUra+98MJYKNXghVgRSJWRHJqMLet7nCxiuUO+YXTh5FKPhj0CB1tQ1SD3
            MJAR9guH9+ZXjI08toLqiWQ6GVO/g5gJCVk5EGdFTjuNkGKnpcS8jSTz3oglpvM/
            SxLoSbwWvtLYY0mJSFnfkzwMj2c/dI+c6eWWX8xszPcan939NtPOYjEX3PVjGnXS
            XgG5f1NyGAKRPELe+f7hMnPmhZeq0N75BvjSXAt1elYQtECa0Up53laU0r572Om+
            CsaY8LgzU021Dh9GcaxxPP2ljHLXr1whK497HqsIMU7NvKnQPzr38hfHq1sOyoE=
            =yPjI
            -----END PGP MESSAGE-----
          fp: 76AF39813C2297E8F98C542D42436A07A9BA1DE0
    version: 3.13.1
