apiVersion: v1
kind: Secret
metadata:
    name: uptime-kuma-admin-credentials
    namespace: uptime-kuma
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:+vIHP+qkWw==,iv:aGWh9Jk8bfKOOIVCkkWl/tAwNpsSORi6+uQWPtD8Qko=,tag:q2bvvuNrnkxHbsfD8QfPeQ==,type:str]
    password: ENC[AES256_GCM,data:mT1kxhNg4z+eLh5c,iv:z4HJsEHjKZ9DFCh5GUxu1cziXmH3JmVvQHQWc9bZqi0=,tag:QJUDYTNh+dfXwAjz8f2x6Q==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-02T17:53:25Z"
    mac: ENC[AES256_GCM,data:/OEzis2lUQF+8Sk2TAmhDWxk29bZQYuAI3fjqbFxfI0nNP1OT9JhmjWknHlqCcpkeNgmNPl+XIH2Cwja73BpDWVAAuwZ5Je67Gay8E6Ib5T+SH6zE7ht6ELczb428d73cYuBDK9U/w9ZGMVk7UcssSiV5ktzm2h0Td9zC2bWI3A=,iv:kURvlUgEI8uAoS2PirCM55Us7Eddbi1C8iAV5e87SUc=,tag:ssy73TqVzwKhrj8ZJvCdug==,type:str]
    pgp:
        - created_at: "2026-08-02T17:53:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+iIV7UXPYO1ARAAqsrWn58uao5WMeW8kBWzlOvr7ZUPA3uDLiwekQTJg638
            JcdBe4Wto2IXs2L3LTYCNVxbv8TdZyCMEhIpjN4psISGSbOPFVncHu+ZzTavwB6b
            +Q+FHn4Op/pZSdnWlYc4omOZXvE/RQFVZR3d0puTdPeV9iM8wtbqieBeN4zS+J0K
            7UWDd25YZFj/dtSPevkJ2Fs8TTbtf5EZ/21qlTIU7zvB7gLqNR7TOtwb46Pn60Pw
            euX+6BlKfDvWTSQVz5BGRPMxD03Ve8B7Ve8c68WRNZAfLR5kkmEBVOzMg7i8LEUq
            IeiTOxTszo7clpIAY7fDogxkVd0Go319XnZ9BM0oEWCm0r5JHI0PrrhT9jEMpXm9
            1HDLKyZfaMMAwyI3V9YH13DxFDs9N6mVr5l4jxs3yS0exXGy1wkHRxT4ijimPQxH
            EVqMhWB8MzggnxtBHkLCd24wLLUXQqFOIFjlskd5k5gcSmGPt/ap2ovh699U6Vgb
            zWTn78JE/k9k1ao5DbbEuG6HtknsmqigoX2kkQHaQLL3gEStr8/236cq/mOJqEZA
            yqInzCCXNejiJYAC6V3JYJTAPar9ySv4OoSwjRlcbtboYeF8PzHOsgvouZ19VkaT
            r7dpiTgfxaTmx1+4RywrtACAXytLIuGgqWIt9ttjFiKXaw6ecIhgTEHZ+tE690jS
            XgE/ChkdiTlw8FT2pIDlkXknTiJp86Hr+Hx3WcbLukKK/v5anBAnxIeteLadiOh5
            33i7OvWqW6GgI95n1YNSURUbbEhf3vZFzU6cAZRzpYPEqhLOwOYeHuK4TZKscLs=
            =88ai
            -----END PGP MESSAGE-----
          fp: 76AF39813C2297E8F98C542D42436A07A9BA1DE0
    version: 3.13.1
