apiVersion: v1
kind: Secret
metadata:
    name: uptime-kuma-admin-credentials
    namespace: uptime-kuma
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:isdWzEs=,iv:Zb39bJ03OlusoomChFpsRzR8Ot6zztlXfOifP4TSh4o=,tag:r2Gz0MqFszLN0HhNku4wng==,type:str]
    password: ENC[AES256_GCM,data:aJ5OFwq/jou2JyDby5zEozdofDJSmHfrDLS/gb2oPeQ=,iv:PZK5jy2BLB/as126sg9nz8y8kWfqn3WNRpri/XJwung=,tag:EIOio+CwSVa6rc0f++p+OA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-02T16:11:16Z"
    mac: ENC[AES256_GCM,data:c8dlSjLMqToJjnSEOcBXyDvRw0p4tZfAvohax/unDezTuaWCE+ByMY6TVe8N40OrzuS+55pEhTn2Zut3YBH9aCR696PYac98jdT8dh2pSQcm9g/uMnELru7Ub5EQgDVqihl0fkSW8gxg9UNgLpJNXela21E/oEmnuzpHfyWTu5I=,iv:2sWGYAHcHBN19Kg0aXQlnrPUwX1vmH6Z2UtvQgyBOC0=,tag:FCLRjnHCzMHlqhmdxkRX9g==,type:str]
    pgp:
        - created_at: "2026-08-02T16:11:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+iIV7UXPYO1ARAAlD7HwqXcLiosINjE2EP/ktbWk9J3O8WgJ04uut3utkB0
            MuJtv2Wunm4zpN6pEeh9PiK2P6qelP57KJ+tgCHusiK3g+EsJC9tdPmfDoHs/Ahl
            M5O/1MiGchW15nrhYH1iMRsERTGcIBuVPNAXNZLt56fZdGphJ0JUd86qZW3cLSDv
            cxs3vr7etTmceBtZVE2u0Ciu6x0asSm3KaDtBuxshsGYXRGP5tzjHwxfFnq6Aan/
            Opo7S01GD/ghc9sKV16s24i8ACQ3KS+G7NS82nPEOcUufh9qTKL9brFXZJshDKRi
            Ygivl0Bx/rdKpCF8S5BkHCfmQA9ltALDgMJ1TtZL3nErDlWALZhGhImsPE5Ehukr
            oI5ohQQsGpSUf+Y/mxB27wHYVoO1ui85zSDNPHM3jYKUctlGvpz6wUgFV02ZOKeQ
            2eqtXZqEgYrVHyx/nBErOJX722TSQ+tAWVZYps9loEeK2xLx+dQaiHyrTtQ8tYoP
            Hucb8MY+7XkAp3j/AtdTNNPc5+ypVsMQ84ByQMyJMiApmv4qG1au4Hp+PR3No+m7
            Vib2Tik2EuL7UOvL3gLi3FZzjV70Yq/M5hdL9CH6OEd/g9N9OkuHRn5RH7p0FrB1
            7lWFmmMcfOYtrwawAPhrbdEfl/wS2FSzT7+4G+V6PoPD+NNrz10/MggiJHBe/VPS
            XAHCtbnNDW7Ku/qvEUm/VKMJr5u0z3g5MqCoaxlS5jFz36YYFpAP7pE6wUVvx7Mm
            +FtEZNDOWKJJ+MadgLvQNalVrpVoNjO/eWsIHXqOUzWZXBi782pmFoD1DPHj
            =ERgF
            -----END PGP MESSAGE-----
          fp: 76AF39813C2297E8F98C542D42436A07A9BA1DE0
    version: 3.13.1
