apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: uptime-kuma
resources:
  - ../../base/uptime-kuma
  - mariadb-credentials.sops.yaml
  - admin-credentials.sops.yaml
  - admin-bootstrap-job.yml
configMapGenerator:
  - name: uptime-kuma-admin-bootstrap
    namespace: uptime-kuma
    files:
      - admin-bootstrap.js