apiVersion: v1
kind: Secret
metadata:
    name: uptime-kuma-mariadb-credentials
    namespace: uptime-kuma
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:h4+tugCirFpNZRU=,iv:vZtkGPowiFtE58pWs/Yp/HMvBJvB+86ulI60TTpd6Nk=,tag:PTIkkmKXViAUfMGZwJfnxQ==,type:str]
    password: ENC[AES256_GCM,data:RNLZkH93aR3QcSrMqWlOW3+TsQieIC9+YujDlY7WfUo=,iv:ZZwBBYBY5yJpzw5D0U9vsuZGROwf7wT5EDPE73rwnws=,tag:bFgWv1gVnMx3y9a+y5I5hw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-02T15:11:23Z"
    mac: ENC[AES256_GCM,data:dNRbZo/FEGsl+Mn/5PtPVb5j4QQSLVLQGnEKpkhVEpuoWVa6OujJkFPtKfzrGVytPOCI+MK/lbTSVM8/9Gi2go4uTtWrkL7orKaMtado66cAi3zfuM44OY6pGOUCOfXszQTv74cxTqmgqSc5pLyLUSsP79NRGzS/5FQgC3FmM1M=,iv:FxP7dyaevSleJX6BVqEJF4KNHCSakCSofCmM812qxqw=,tag:hHQn4298uqlCs2zdX7AMZg==,type:str]
    pgp:
        - created_at: "2026-08-02T15:11:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+iIV7UXPYO1AQ/9FfYIxSTExBwQGpdleyylw5jn7+R6v4YRCoWIl49qs16p
            TG7LqKpUARe17tdXwa6a3Z3PVn5spjMyetZ40M+KsGLaVQQWglRCOh0uMCnwDUNi
            VkIv3gTq/7CV8RJi/du/dikI77Lvx7SUhEQ6XsM87i8aH11VWFjPmG85SCi5iLie
            7MWpt9ZA4brMMp2xaGPtqxhgfc8Wm+kz3L7uTXQOlqdbMK65CQOIVlLPcQEG5DBQ
            /Fuj6FewUWivXamGsSuW8MP99H0nrE3ouRcwZtAnDwbmM0Wvv3AtwmwLChnaTBz+
            wvBmxWEaN6IdyVZbywn/QnvCC2Gw6wCojDvtTz1p6ExUmSnf0aHbkiaX0qhnevN4
            Oh8zjqAYxgFOlYJlTJoZ0t7FCqQKavQh0SpRGNkdmaFskcC6PioBAKvmxH8jiqbf
            EGf1Fpk4MJNY1YLVNPWKZsSgkJ7GlHVYhDH/bDuFm5K6dMqiY8mFzEbfdScNBc8o
            QoaQB2LLvqJSKebnnI7e/2Hy9UZsBRW37hIlR7eGihUrteI0lP/YFBvUJOlm0xol
            ubSLCHuNeOmn3ioDMwBsWmBISJ/OBi+KEzG70N3VL6TuSl/zRjle80wfdfiXdW+G
            z2VjKpOb1rxJ40jqvfZwom3gGdxXmOrFD8UBBq1J32E0nf6Wd99xEgKGOD0Ot4rS
            XAHqIWIT8J2r0ZR3cze+inaVWjFOCuNklXOHE5mOwVEmWsiJjGQLoPJtUlMfvrG9
            uHjvwpXIQYKhrfTDGLKpc+QHwb0eyEu3/UzwpDJo+aZIxImpmMbfS+Dypg2e
            =85Ia
            -----END PGP MESSAGE-----
          fp: 76AF39813C2297E8F98C542D42436A07A9BA1DE0
    version: 3.13.1
