---
- name: Install sniff using krew
  shell: kubectl krew install sniff
  environment:
    PATH: "/home/kubernetes/.local/bin:/home/kubernetes/bin:/home/kubernetes/.krew/bin/kubectl-krew:{{ ansible_env.PATH }}"