---
- name: Copy install script
  become: true
  become_user: "{{ user }}"
  copy:
    src: install_krew.sh
    dest: "{{ install_script }}"
    mode: 0755

- name: Run bash script to install krew
  become: true
  become_user: "{{ user }}"
  shell: "{{ install_script }}"

- name: Add krew bin to PATH
  become: true
  become_user: "{{ user }}"
  lineinfile:
    path: "{{ bashrc }}"
    line: 'export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"'
    create: yes