name: Ansible lint
permissions:
  contents: read
on:
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/ansible-lint.yaml'
      - 'Ansible/**'
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Ansible
        uses: ./.github/actions/ansible-setup

      - name: Install ansible-lint
        run: |
          pip install ansible-lint

      - name: Run ansible-lint
        working-directory: Ansible
        run: |
          ansible-lint --format pep8 --strict --force-color
