name: .*
permissions:
  contents: read
on:
  workflow_dispatch:
jobs:
  update:
    runs-on: github-runners-clincha
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Set up Ansible
        working-directory: Ansible
        run: |
          pip install -r requirements.txt

      - name: Install Ansible collections
        working-directory: Ansible
        run: |
          ansible-galaxy collection install -r galaxy-requirements.yml

      - name: Setup vault password
        working-directory: Ansible
        run: |
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > vault

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval `ssh-agent -s`
          ssh-add ~/.ssh/id_ed25519

      - name: Set up Kubernetes CLI
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.32.0'

      - name: Deploy kube config
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Run Ansible playbook
        working-directory: Ansible
        run: |
          ansible-playbook update-k8s.yml \
            --inventory inventory/kubernetes-dynamic.proxmox.yml \
            --vault-password-file vault
