name: Ansible Claude Code server
permissions:
  contents: read
on:
  push:
    branches:
      - "master"
    paths:
      - '.github/workflows/ansible-claude.yaml'
      - 'Ansible/**'
  workflow_dispatch:
concurrency:
  group: "claude-hawkfield"
jobs:
  claude:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Set up Ansible
        uses: ./.github/actions/ansible-setup
        with:
          vault-password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          ssh-private-key: ${{ secrets.ANSIBLE_PRIVATE_KEY }}

      - name: Run Ansible playbook
        working-directory: Ansible
        env:
          PROXMOX_TOKEN_SECRET: ${{ secrets.PROXMOX_TOKEN_HAWKFIELD_ANSIBLE }}
          CLAUDE_SSH_PRIVATE_KEY: ${{ secrets.CLAUDE_SSH_PRIVATE_KEY }}
          BW_CLIENT_ID: ${{ secrets.BW_CLIENT_ID }}
          BW_CLIENT_SECRET: ${{ secrets.BW_CLIENT_SECRET }}
          BW_MASTER_PASSWORD: ${{ secrets.BW_MASTER_PASSWORD }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          ansible-playbook claude.yml \
            --inventory inventory/hawkfield.proxmox.yml \
            --vault-password-file vault
