name: Ansible base configuration
permissions:
  contents: read
on:
  push:
    branches:
      - "master"
    paths:
      - '.github/workflows/ansible-base.yaml'
      - 'Ansible/**'
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"
concurrency:
  group: "${{github.workflow}}"
jobs:
  base:
    runs-on: github-runners-clincha
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Set up Ansible
        working-directory: Ansible
        run: |
          pip install -r requirements.txt

      - name: Install Ansible collections
        working-directory: Ansible
        run: |
          ansible-galaxy collection install -r galaxy-requirements.yml

      - name: Setup vault password
        working-directory: Ansible
        run: |
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > vault

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval `ssh-agent -s`
          ssh-add ~/.ssh/id_ed25519

      - name: Run Ansible playbook
        working-directory: Ansible
        run: |
          ansible-playbook base.yml \
            --inventory inventory/kubernetes-dynamic.proxmox.yml \
            --vault-password-file vault
