name: Ansible Lint
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ansible-lint.yaml'
      - 'Ansible/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Set up Ansible
        working-directory: Ansible
        run: |
          pip install -r requirements.txt

      - name: Install ansible-lint
        run: |
          pip install ansible-lint

      - name: Run ansible-lint
        run: |
          ansible-lint Ansible/
