name: Ansible update Proxmox
permissions:
  contents: read
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
concurrency:
  group: "${{github.workflow}}"
jobs:
  hawkfield:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Set up Ansible
        working-directory: Ansible
        run: |
          pip install -r requirements.txt

      - name: Install Ansible collections
        working-directory: Ansible
        run: |
          ansible-galaxy collection install -r galaxy-requirements.yml

      - name: Setup vault password
        working-directory: Ansible
        run: |
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > vault

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval `ssh-agent -s`
          ssh-add ~/.ssh/id_ed25519

      - name: Run Ansible playbook (Hawkfield)
        working-directory: Ansible
        run: |
          ansible-playbook update-proxmox.yml \
            --inventory inventory/hawkfield.proxmox.yml \
            --vault-password-file vault

  london:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Set up Ansible
        working-directory: Ansible
        run: |
          pip install -r requirements.txt

      - name: Install Ansible collections
        working-directory: Ansible
        run: |
          ansible-galaxy collection install -r galaxy-requirements.yml

      - name: Setup vault password
        working-directory: Ansible
        run: |
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > vault

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval `ssh-agent -s`
          ssh-add ~/.ssh/id_ed25519

      - name: Run Ansible playbook (London)
        working-directory: Ansible
        run: |
          ansible-playbook update-proxmox.yml \
            --inventory inventory/london.proxmox.yml \
            --vault-password-file vault
