name: Ansible base configuration
permissions:
  contents: read
on:
  push:
    branches:
      - "master"
    paths:
      - '.github/workflows/ansible-base.yaml'
      - 'Ansible/**'
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
jobs:
  hawkfield:
    runs-on: ubuntu-latest
    concurrency:
      group: "cluster-hawkfield"
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Set up Ansible
        uses: ./.github/actions/ansible-setup
        with:
          vault-password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          ssh-private-key: ${{ secrets.ANSIBLE_PRIVATE_KEY }}

      - name: Run Ansible playbook (Hawkfield)
        working-directory: Ansible
        env:
          PROXMOX_TOKEN_SECRET: ${{ secrets.PROXMOX_TOKEN_HAWKFIELD_ANSIBLE }}
        run: |
          ansible-playbook base.yml \
            --inventory inventory/hawkfield.proxmox.yml \
            --vault-password-file vault

  london:
    runs-on: ubuntu-latest
    concurrency:
      group: "cluster-london"
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Set up Ansible
        uses: ./.github/actions/ansible-setup
        with:
          vault-password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          ssh-private-key: ${{ secrets.ANSIBLE_PRIVATE_KEY }}

      - name: Run Ansible playbook (London)
        working-directory: Ansible
        env:
          PROXMOX_TOKEN_SECRET: ${{ secrets.PROXMOX_TOKEN_LONDON_ANSIBLE }}
        run: |
          ansible-playbook base.yml \
            --inventory inventory/london.proxmox.yml \
            --vault-password-file vault
