name: Ansible Update Kubernetes
on:
  push:
    branches:
      - master
    paths:
      - 'Ansible/**'
      - '.github/workflows/ansible-update-k8s.yaml'
  workflow_dispatch:
jobs:
  update:
#    strategy:
#      fail-fast: true
#      max-parallel: 1
#      matrix:
#        node:
#          - "k8s-master-1"
#          - "k8s-master-2"
#          - "k8s-worker-3"
    runs-on: github-runners-clincha
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Set up Ansible
        run: |
          pip install ansible distlib

      - name: Install Ansible collections
        working-directory: Ansible
        run: |
          ansible-galaxy collection install -r galaxy-requirements.yml

      - name: Run Ansible playbook
        working-directory: Ansible
        run: |
          ansible-playbook update.yml \
            --inventory inventory/kubernetes-dynamic.proxmox.yml \
            --limit "k8s-master-1"
#
#      - name: Set up Kubernetes CLI
#        uses: azure/setup-kubectl@v4
#        with:
#          version: 'latest'
#
#      - name: Deploy kube config
#        run: |
#          mkdir -p $HOME/.kube
#          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
#          chmod 600 $HOME/.kube/config
#
#      - name: Apply Kubernetes manifests
#        run: |
#          kubectl drain ${{ matrix.node }} --ignore-daemonsets --delete-local-data
