name: Kubernetes Elastic Finance deployment
permissions:
  contents: read
on:
  push:
    branches:
      - master
    paths:
      - 'kubernetes/elastic-finance/**'
      - '.github/workflows/k8s-elastic-finance.yaml'
  workflow_dispatch:
jobs:
  apply:
    env:
      CHART_VERSION: 1.9.0
      NAMESPACE: elastic-finance
    runs-on: github-runners-clincha
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kubernetes CLI
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.32.0'

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: 'v3.18.2'

      - name: Deploy kube config
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Create namespace
        working-directory: kubernetes/elastic-finance
        run: |
          kubectl apply -f namespace.yml

      - name: Create ingress certificates
        working-directory: kubernetes/elastic-finance
        run: |
          kubectl apply -f certificates.yml

      - name: Install the Elastic Finance using Helm
        working-directory: kubernetes/elastic-finance
        run: |
          helm repo add elastic https://helm.elastic.co
          helm repo update
          helm upgrade --install --wait elastic-finance elastic/eck-stack \
            --version ${{ env.CHART_VERSION }} \
            --namespace ${{ env.NAMESPACE }} --create-namespace \
            --values values.yml