name: Traefik Kubernetes Deployment
on:
  workflow_dispatch:
jobs:
  apply:
    env:
      TRAEFIK_VERSION: 36.0.0
      NAMESPACE: traefik
    runs-on: github-runners-clincha
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kubernetes CLI
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: 'latest'

      - name: Deploy kube config
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Install Traefik using Helm
        working-directory: kubernetes/traefik
        run: |
          helm repo add traefik https://traefik.github.io/charts
          helm repo update
          helm upgrade --install traefik traefik/traefik \
            --version ${{ env.TRAEFIK_VERSION }} \
            --namespace ${{ env.NAMESPACE }} --create-namespace \
            -f values.yml

      - name: Apply Traefik certificate
        working-directory: kubernetes/traefik
        run: |
          kubectl apply -f certificate.yml

