name: template-terraform
on:
  workflow_call:
    inputs:
      command:
        type: string
        default: "apply"
        description: "The terraform command to run"
        required: true
      wg_allowed_ips:
        type: string
        default: "10.1.5.1/32,10.1.5.2/32,192.168.1.11/24,10.1.1.1/24,10.1.2.1/24,10.1.3.1/24,0.0.0.0/0"
        description: "The IP addresses in HL that this host can access"
        required: true
      wg_address:
        type: string
        default: "10.1.5.2/32"
        description: "The WireGuard address to use for this host"
        required: true
      wg_dns:
        type: string
        default: "10.1.5.1"
        description: "The WireGuard DNS server"
        required: true
    secrets:
      ARM_ACCESS_KEY:
        required: true
        description: "The Azure storage account access key"
      ANSIBLE_PK:
        required: true
        description: "The Ansible private key"
      BRISTOL_PROXMOX_TOKEN_SECRET:
        required: true
        description: "The HL Proxmox token secret"
      HL_PRIVATE_KEY:
        required: true
        description: "The HL WireGuard private key"
      HL_PRESHARED_KEY:
        required: true
        description: "The HL WireGuard preshared key"
      HL_ENDPOINT:
        required: true
        description: "The HL WireGuard endpoint"
      DOCKERHUB_PASSWORD:
        required: true
        description: "The Docker Hub password"
jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: "Install WireGuard"
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard
          # https://superuser.com/questions/1500691/usr-bin-wg-quick-line-31-resolvconf-command-not-found-wireguard-debian
          ln -s /usr/bin/resolvectl /usr/local/bin/resolvconf

      - name: "Create WireGuard config"
        run: |
          sudo mkdir -p /etc/wireguard
          sudo chmod 700 /etc/wireguard
          sudo touch /etc/wireguard/wg0.conf
          sudo chmod 600 /etc/wireguard/wg0.conf
          sudo bash -c "cat > /etc/wireguard/wg0.conf" << EOF
          [Interface]
          PrivateKey = ${{ secrets.HL_PRIVATE_KEY }}
          Address = ${{ inputs.wg_address }}
          DNS = ${{ inputs.wg_dns }}
          
          [Peer]
          PublicKey = 6/tGUsqU3ib5LEEua2cLCUxSDFpiEFhOT0sGkqz0LHk=
          PresharedKey = ${{ secrets.HL_PRESHARED_KEY }}
          AllowedIPs = ${{ inputs.wg_allowed_ips }}
          Endpoint = ${{ secrets.HL_ENDPOINT }}
          EOF

      - name: "Start WireGuard"
        run: |
          sudo wg-quick up wg0
          sudo wg
          ping 192.168.1.11 -c 3

      - name: Log in to docker.io
        uses: redhat-actions/podman-login@v1.6
        with:
          username: "clincha"
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          registry: docker.io

      - name: Apply Terraform
        run: make ARM_ACCESS_KEY=${{ secrets.ARM_ACCESS_KEY }}
        env:
          TF_VAR_ansible_id_rsa: ${{ secrets.ANSIBLE_PK }}
          TF_VAR_bristol_proxmox_token_secret: ${{ secrets.BRISTOL_PROXMOX_TOKEN_SECRET }}

      - name: "Stop WireGuard"
        if: always()
        run: |
          sudo wg-quick down wg0
          sudo rm -rf /etc/wireguard