name: Build container image
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      desc:
        description: "desc"
        required: false
jobs:
  build:
    runs-on: [ self-hosted, init ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: redhat-actions/podman-login@v1.6
        with:
          username: "clincha"
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          registry: docker.io

      - name: Build image
        run: make build

      - name: Apply Terraform
        run: make build
        env:
          TF_VAR_ansible_id_rsa: ${{ secrets.ANSIBLE_PK }}
          TF_VAR_bristol_proxmox_token_secret: ${{ secrets.BRISTOL_PROXMOX_TOKEN_SECRET }}