name: Build container image
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to docker.io
        uses: redhat-actions/podman-login@v1.6
        with:
          username: "clincha"
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          registry: docker.io

      - name: Apply Terraform
        run: make
        env:
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
          TF_VAR_ansible_id_rsa: ${{ secrets.ANSIBLE_PK }}
          TF_VAR_bristol_proxmox_token_secret: ${{ secrets.BRISTOL_PROXMOX_TOKEN_SECRET }}