name: Build container image
on:
  push:
    tags:
      - 'v*'
defaults:
  run:
    shell: bash -leo pipefail {0}
jobs:
  build:
    runs-on: [ self-hosted, init ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: "clincha"
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build image
        run: make build

      - name: Apply Terraform
        run: make build
        env:
          TF_VAR_ansible_id_rsa: ${{ secrets.ANSIBLE_PK }}
          TF_VAR_bristol_proxmox_token_secret: ${{ secrets.BRISTOL_PROXMOX_TOKEN_SECRET }}